#!bin/csh
# compiler:
F_COMPILER = gfortran
#FFLAGS = -e -O5
#FFLAGS = -m64 -mcmodel=medium -pedantic -Wall -Wsurprising -ffixed-line-length-132 -g
FFLAGS = -Wsurprising -ffixed-line-length-132 -O3
#FFLAGS = -pedantic -Wall -Wsurprising -ffixed-line-length-132 -g
# directorio de instalacion del ejecutable:
#dir_inst = ../
#dir_prog = ./lib
#
FSOURCE = a_alphaCO.f \
          hrsl_alphaCO.f \
          STU_alphaCO.f \
	  sigmam_alphaCO.f \
          e_alphaCO.f \
          fra_u_usdss.f\
          fraU.f\
          respu.f\
          respk.f\
          frausdss.f\
          frausdss004.f\
          respusdss.f\
          xflabs.f\
          fracat.f\
          respij.f\
          respic.f\
          FNORM.f \
          loca.f \
          matinx.f \
          limf.f \
	  dpythag.f \
	  dsvbksb.f \
	  dsvdcmp.f \
	  respv.f \
	  respb.f \
	  hunt.f \
	  polint.f \
	  indexx.f \
	  remn.f

FOBJECT = a_alphaCO.o \
          hrsl_alphaCO.o \
          STU_alphaCO.o \
	  sigmam_alphaCO.o \
          e_alphaCO.o \
          fra_u_usdss.o\
          fraU.o\
          respu.o\
          respk.o\
          frausdss.o\
          frausdss004.o\
          respusdss.o\
          xflabs.o\
          fracat.o\
          respij.o\
          respic.o\
          FNORM.o \
          loca.o \
          matinx.o \
          limf.o \
	  dpythag.o \
	  dsvbksb.o \
	  dsvdcmp.o \
	  respv.o \
	  respb.o \
	  hunt.o \
	  polint.o \
	  indexx.o \
	  remn.o
	  
# default rule to create program
a: $(FOBJECT)
	$(F_COMPILER) -o $@ $(FOBJECT) $(FFLAGS)
	mv $@ ../a_alphaCO

.f.o: $(FSOURCE)
	$(F_COMPILER) -c $(FSOURCE) $(FFLAGS)

