      program readfits_spectrum

C  Read a FITS image and determine the minimum and maximum pixel value.
C  Rather than reading the entire image in
C  at once (which could require a very large array), the image is read
C  in pieces, 100 pixels at a time.  

      integer status,unit,readwrite,blocksize,naxes(2),nfound
      integer group,firstpix,nbuffer,npixels,i
      real*8  crpix1, crval1, cdelt1
      real*8  datamin,datamax,nullval,wave(100000),buffer(100000)
      logical anynull
      character filename*80, outfile*80

C  The STATUS parameter must always be initialized.
      status=0

C  Get an unused Logical Unit Number to use to open the FITS file.
      call ftgiou(unit,status)

C  Open the input FITS file
      call getarg(1,filename)
      call getarg(2,outfile)

      print *, filename
      readwrite=0
      call ftopen(unit,filename,readwrite,blocksize,status)

C  Determine the size of the spectrum
      call ftgknj(unit,'NAXIS',1,2,naxes,nfound,status)
      npixels=naxes(1)
C      print *, npixels

C  Check that it found the NAXIS1 keyword.
      if (npixels .le. 0) then
          print *,'READ_SPECTRUM failed to read the NAXIS1 keyword.'
          return
       end if

C  Initialize variables and printing the number of pixels in the STDOUT
      group=1
      firstpix=1
      nullval=-999
      datamin=1.0E30
      datamax=-1.0E30

C  Read the header, build a vector with the Wavelength values
      call readheader(filename,crpix1,crval1,cdelt1)

C  Read the values of the spectrum
      call ftgpvd(unit,group,firstpix,npixels,nullval,
     &  	  buffer,anynull,status)

C  Writing spectrum in ASCII
      OPEN(99,FILE=outfile,STATUS='REPLACE')
      do i=1,npixels
C	 print *, crval1 + cdelt1 * (i - crpix1), buffer(i)
         WRITE(UNIT=99, FMT="(F9.3,3x,D21.15)") 
     &	 crval1 + cdelt1 * (i - crpix1), buffer(i)
      end do
      CLOSE(99)
      print *, npixels, crpix1,crval1,cdelt1

C  The FITS file must always be closed before exiting the program. 
C  Any unit numbers allocated with FTGIOU must be freed with FTFIOU.
      call ftclos(unit, status)
      call ftfiou(unit, status)

C  Check for any error, and if so print out error messages.
C  The PRINTERROR subroutine is listed near the end of this file.
      if (status .gt. 0)call printerror(status)
      end

C *************************************************************************
      subroutine readheader(filename,crpix1,crval1,cdelt1)

C  Print out all the header keywords in all extensions of a FITS file

      integer status,unit,readwrite,blocksize,nkeys,nspace,hdutype,i,j
      real*8  crpix1, crval1, cdelt1
      character filename*80,record*80

C  The STATUS parameter must always be initialized.
      status=0

C  Get an unused Logical Unit Number to use to open the FITS file.
      call ftgiou(unit,status)
      print *, ""

C     open the FITS file, with read-only access.  The returned BLOCKSIZE
C     parameter is obsolete and should be ignored. 
      readwrite=0
      call ftopen(unit,filename,readwrite,blocksize,status)

C  Read the value for the CRVAL1, CDELT1 and CRPIX1 keywords
      call ftgkyd(unit,'CRPIX1',crpix1,comment,status)     
      call ftgkyd(unit,'CRVAL1',crval1,comment,status)     
      call ftgkyd(unit,'CDELT1',cdelt1,comment,status)     

C  The FITS file must always be closed before exiting the program. 
C  Any unit numbers allocated with FTGIOU must be freed with FTFIOU.
      call ftclos(unit, status)
      call ftfiou(unit, status)

C  Check for any error, and if so print out error messages.
C  The PRINTERROR subroutine is listed near the end of this file.
      if (status .gt. 0) call printerror(status)
      end
C *************************************************************************
      subroutine printerror(status)

C  This subroutine prints out the descriptive text corresponding to the
C  error status value and prints out the contents of the internal
C  error message stack generated by FITSIO whenever an error occurs.

      integer status
      character errtext*30,errmessage*80

C  Check if status is OK (no error); if so, simply return
      if (status .le. 0) return

C  The FTGERR subroutine returns a descriptive 30-character text string that
C  corresponds to the integer error status number.  A complete list of all
C  the error numbers can be found in the back of the FITSIO User's Guide.
      call ftgerr(status,errtext)
      print *,'FITSIO Error Status =',status,': ',errtext

C  FITSIO usually generates an internal stack of error messages whenever
C  an error occurs.  These messages provide much more information on the
C  cause of the problem than can be provided by the single integer error
C  status value.  The FTGMSG subroutine retrieves the oldest message from
C  the stack and shifts any remaining messages on the stack down one
C  position.  FTGMSG is called repeatedly until a blank message is
C  returned, which indicates that the stack is empty.  Each error message
C  may be up to 80 characters in length.  Another subroutine, called
C  FTCMSG, is available to simply clear the whole error message stack in
C  cases where one is not interested in the contents.
      call ftgmsg(errmessage)
      do while (errmessage .ne. ' ')
          print *,errmessage
          call ftgmsg(errmessage)
      end do
      end
